# Generated by Django 5.2.7 on 2025-10-18 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_userprofile_activated_at_userprofile_activated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountactivationrequest",
            name="company_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="accountactivationrequest",
            name="company_registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="accountactivationrequest",
            name="username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("company", "Company Account"),
                    ("individual", "Individual Account"),
                ],
                default="individual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="documents_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="documents_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="Email verified"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="accountactivationrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("company_registration", "Company Registration"),
                    ("individual_registration", "Individual Registration"),
                    ("user_invitation", "User Invitation"),
                    ("user_registration", "User Registration"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="accountactivationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("documents_required", "Documents Required"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DocumentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            (
                                "business_registration",
                                "Business Registration Certificate",
                            ),
                            ("tax_certificate", "Tax Registration Certificate"),
                            ("cac_certificate", "CAC Certificate"),
                            ("director_id", "Director ID Document"),
                            ("utility_bill", "Utility Bill"),
                            ("bank_statement", "Bank Statement"),
                            ("individual_id", "Individual ID Document"),
                            ("passport", "Passport"),
                            ("license", "Professional License"),
                            ("other", "Other Document"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to="registration_documents/"
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("requires_revision", "Requires Revision"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "activation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.accountactivationrequest",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["activation_request", "document_type"],
                        name="core_docume_activat_0fb161_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_docume_status_da7fc5_idx",
                    ),
                ],
            },
        ),
    ]
