# Generated by Django 5.2.7 on 2025-10-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_accountactivationrequest_company_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="registration_number",
            field=models.CharField(
                blank=True, help_text="Company registration number", max_length=100
            ),
        ),
    ]
