# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('core', '0002_add_multitenant_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='expensecategory',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='recurringexpense',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='core.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to='auth.user'),
        ),
    ]
