# Generated by Django 5.2.7 on 2025-10-18 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_notificationtemplate_usernotificationpreference_and_more"),
        ("expenses", "0002_rename_user_to_created_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expensecategory",
            unique_together={("company", "name")},
        ),
    ]
