# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
        ('core', '0002_add_multitenant_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='contractor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='core.company'),
        ),
    ]
